import { Router } from "express";
import authRouter from "../modules/auth/auth-route";
import departmentRouter from "../modules/departments/department-route";
import userRouter from "../modules/users/user-route";
import attendanceRouter from "../modules/attendance/attendance-route";
import leaveRouter from "../modules/leaves/leave-route";
import payrollRouter from "../modules/payroll/payroll-route";
import performanceRouter from "../modules/performance/performance-route";
import deviceRouter from "../modules/devices/device-route";
import geofenceRouter from "../modules/geofence/geofence-route";
import recruitmentRouter from "../modules/recruitment/recruitment-route";
import onboardingRouter from "../modules/onboarding/onboarding-route";
import policyRouter from "../modules/policies/policy-route";
import academyRouter from "../modules/academy/academy-route";
import orgChartRouter from "../modules/org-chart/org-chart-route";
import lifecycleRouter from "../modules/lifecycle/lifecycle-route";
import okrRouter from "../modules/okr/okr-route";
import discRouter from "../modules/disc/disc-route";
import feedback360Router from "../modules/feedback360/feedback360-route";
import gradingRouter from "../modules/grading/grading-route";
import notificationRouter from "../modules/notification/notification-route";
import dashboardRouter from "../modules/dashboard/dashboard-routes";
import employeeStatusRouter from "../modules/employee-status/employee-status-route";

const mainRouter = Router();

mainRouter.use("/v1/auth", authRouter);
mainRouter.use("/v1/departments", departmentRouter);
mainRouter.use("/v1/users", userRouter);
mainRouter.use("/v1/attendance", attendanceRouter);
mainRouter.use("/v1/leaves", leaveRouter);
mainRouter.use("/v1/payroll", payrollRouter);
mainRouter.use("/v1/performance", performanceRouter);
mainRouter.use("/v1/devices", deviceRouter);
mainRouter.use("/v1/geofences", geofenceRouter);
mainRouter.use("/v1/recruitment", recruitmentRouter);
mainRouter.use("/v1/onboarding", onboardingRouter);
mainRouter.use("/v1/policies", policyRouter);
mainRouter.use("/v1/academy", academyRouter);
mainRouter.use("/v1/org-chart", orgChartRouter);
mainRouter.use("/v1/lifecycle", lifecycleRouter);
mainRouter.use("/v1/okr", okrRouter);
mainRouter.use("/v1/disc", discRouter);
mainRouter.use("/v1/feedback-360", feedback360Router);
mainRouter.use("/v1/grading", gradingRouter);
mainRouter.use("/v1/notifications", notificationRouter);
mainRouter.use("/v1/employee", dashboardRouter);
mainRouter.use("/v1/employee-statuses", employeeStatusRouter);

export default mainRouter;
